### ISSUE TITLE
Add login capability

### ISSUE THREAD

**Issue by lacuchilla** [lacuchilla/AdaInternshipList#4]
People should be able to sign in as a student or as a staff member. Anyone who is not signed in will only have access to the index page. Staff can do all CRUD operations on Companies and People. Students can CRUD people, but can only update info on companies.

**Comment by lgranger** [comment]
Do you want signup with a bcrypt style thing or a oauth with github or something?

**Comment by lacuchilla** [comment]
Hmmmmmm. Since all C4 adies have a github, using oauth would make sense, but not all staff members necessarily have a github account. I wonder if there's a way to limit who can create a student account just to C4 adies and who can create ada staff accounts to just staff members.

**Comment by lgranger** [comment]
I'd like to give this issue a try with git hub for students and git hub or something else for staff?

**Comment by lacuchilla** [comment]
Have at it, Lauren. It's yours.

**Comment by lacuchilla** [comment]
This is great, Lauren! Thanks so much for adding in the login capability. Awesome job.
